### ISSUE TITLE
Bug in T2Star example

### ISSUE THREAD

**Issue by JSousa-UoL** [QIB-Sheffield/MDR-Library#1]
Hi @KanishkaS , I had the following error while testing this:
```
c:\Users\md1jgra\Desktop\MDR-Library
skipped, no AcquisitionTime: 0
Traceback (most recent call last):
  File "c:\Users\md1jgra\Desktop\MDR-Library\test_MDR\MDR_test_main.py", line 26, in <module>
    MDR_test_T2star.main()
  File "c:\Users\md1jgra\Desktop\MDR-Library\test_MDR\MDR_test_T2star.py", line 72, in main
    iBEAt_test_T2star(Elastix_Parameter_file_PATH, output_dir, sorted_slice_files, ArrayDicomiBEAt, image_parameters, filenameDCM, lstFilesDCM)
TypeError: iBEAt_test_T2star() takes 6 positional arguments but 7 were given
```

I checked the "MDR_test_T2Star" file and the call is:

`iBEAt_test_T2star(Elastix_Parameter_file_PATH, output_dir, sorted_slice_files, ArrayDicomiBEAt, image_parameters, filenameDCM, lstFilesDCM)`

In which there are 7 input arguments, but the function a few lines below has 6:
`def iBEAt_test_T2star(Elastix_Parameter_file_PATH, output_dir, ArrayDicomiBEAt, image_parameters, filenameDCM, lstFilesDCM)`

If I remove the 'sorted_slice_files' variable, the code continues although I don't know if it's doing the right thing because it's not using the 'sorted_slice_files'

**Comment by KanishkaS** [comment]
Thanks for the feedback, Joao. Clearly not a good idea to test code first and then make edits later! fixed now ;)
You don't need 'sorted_slice_files' - the DICOMs are sorted according to T2* echo times. I have updated the changes and it should run now and the results should be correct - look the final registration results to confirm.
